<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign Up_hubspot-conversations-iframe</name>
   <tag></tag>
   <elementGuidId>faea8e43-5b24-4cf5-a905-0d9883b11c98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hubspot-conversations-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='hubspot-conversations-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6710b690-7cc3-474c-9cd3-aef73d506759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.hubspot.com/conversations-visitor/20857492/threads/utk/d690c0bf1364484fb95c5854e418ec5a?uuid=86f76df84a204a6c9d363569f695a179&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=develop-v2.t2d2.ai&amp;inApp53=false&amp;messagesUtk=d690c0bf1364484fb95c5854e418ec5a&amp;url=https%3A%2F%2Fdevelop-v2.t2d2.ai%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false</value>
      <webElementGuid>67f0dc6e-dc6b-475e-9e2d-f69266c3715b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hubspot-conversations-iframe</value>
      <webElementGuid>d2b8df16-4462-49c9-bd2e-0c8729fc302c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>9c698b07-07e9-4cf0-863d-831dca5c3ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chat Widget</value>
      <webElementGuid>a5c94a7a-d6f6-4180-8028-b44c5f94c0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>chat-widget-iframe</value>
      <webElementGuid>936a4a91-ebb9-48ba-b869-7447b7fd90a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubspot-conversations-iframe&quot;)</value>
      <webElementGuid>ec4f28f7-3b11-4458-995c-c5d76e09e602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='hubspot-conversations-iframe']</value>
      <webElementGuid>904bbea6-f62e-4915-9c5b-d080a545109a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hubspot-messages-iframe-container']/iframe</value>
      <webElementGuid>301b1d17-0c81-4e56-9d7c-2d22a57c143e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2a703c65-f90c-42c6-9d53-7b129f24e4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.hubspot.com/conversations-visitor/20857492/threads/utk/d690c0bf1364484fb95c5854e418ec5a?uuid=86f76df84a204a6c9d363569f695a179&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=develop-v2.t2d2.ai&amp;inApp53=false&amp;messagesUtk=d690c0bf1364484fb95c5854e418ec5a&amp;url=https%3A%2F%2Fdevelop-v2.t2d2.ai%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false' and @id = 'hubspot-conversations-iframe']</value>
      <webElementGuid>c4f898f1-bc08-4520-a6ec-4b741193c579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
